---
spring:
  profiles: replica1
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica1
  client:
    serviceUrl:
      defaultZone: http://replica2:8003/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8002
---
spring:
  profiles: replica2
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica2  #指定主机地址
  client:
    serviceUrl:
      defaultZone: http://replica1:8002/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8003
