#eureka:
#  client:
#    register-with-eureka: true #注册到Eureka的注册中心
#    fetch-registry: true #获取注册实例列表
#    service-url:
#      defaultZone: http://replica1:8002/eureka/,http://replica2:8003/eureka/ #同时注册到两个注册中心

spring:
  application:
    name: shop-gateway
    cloud:
      consul: #Consul服务注册发现配置
        host: localhost
        port: 8500
        discovery:
          service-name: ${spring.application.name}

server:
  port: 9000
#zuul:
#  #路由规则
#  routes:
#    shop-cate-api: #微服务的名字 spring.application.name
#      path: /cates/** #对应访问的路径
#    shop-goods-api:
#      path: /goods/**
#    shop-member-api:
#      path: /members/**
#    shop-cart-api:
#      path: /carts/**
fh:
  shop:   #checkUrls 配置的是登录后才能访问的接口
    checkUrls: api/members/logout,api/members/findMember,api/carts/addItem,api/carts/findCart,api/carts/findCartCount,api/carts/deleteCartItem,api/carts/deleteBatchCartItem
